name: new landingzone
description: create a new landingzone
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the form below to create a new landingzone.

  - type: input
    id: labName
    attributes:
      label: lab Name
      description: 
      placeholder: bigData
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: environment
      multiple: false
      description:
      options: 
        - test
        - dev
        - uat
        - prod
      default: 0
    validations:
      required: true

  - type: dropdown
    id: managementGroupName
    attributes:
      label: management group name
      multiple: false
      description:
      options: 
        - online-prod
        - platform-prod
        - playground-prod
      default: 0
    validations:
      required: true

  - type: dropdown
    id: managementGroupHierarchy
    attributes:
      label: management group hierarchy
      multiple: false
      description:
      options: 
        - prod
        - test
      default: 0
    validations:
      required: true

  - type: dropdown
    id: location
    attributes:
      label: location
      description: 
      multiple: false
      options:
      - FranceCentral
      default: 0
    validations:
      required: true

  - type: input
    id: subscriptionId
    attributes:
      label: subscription Id
      description: 
      placeholder: 84e64f94-714d-4c07-9f03-f07af8380b36
    validations:
      required: true

  - type: input
    id: budget
    attributes:
      label: budget
      description: 
      placeholder: "100"
    validations:
      required: true

  - type: input
    id: githubOrganizationName
    attributes:
      label: GitHub organization name
      description: 
      placeholder: gazelle-cloud
    validations:
      required: true

  - type: input
    id: githubRepoName
    attributes:
      label: GitHub repo name
      description:
      placeholder: landingzone
    validations:
      required: true

  - type: input
    id: ownerEmail
    attributes:
      label: owner email
      description: pam param
      placeholder: param@gazelle.cloud
    validations:
      required: true

  - type: input
    id: engineer
    attributes:
      label: tag engineer
      description: pam param
      placeholder: foo@gazelle.cloud
    validations:
      required: true
