name: Destory test environment

on:
  workflow_dispatch:
    inputs:
      topLevelManagementGroup:
        required: true
        default: 'gazelle-test'
      managementSubscriptionId:
        required: true
        default: 'ca29cb06-f5f6-4116-9061-493426c4d70e'

permissions:
  id-token: write
  contents: read
  
jobs:
  cancel-landingzone:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ vars.AZURE_PLATFORM_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID}}
        allow-no-subscriptions: true
        enable-AzPSSession: true

    - name: move subscriptions
      uses: azure/powershell@v2
      with:
        azPSVersion: "latest"
        inlineScript: |
          function move-subscriptions {
            param (
                [Parameter(Mandatory = $true)]
                [string]$managementGroup
                [Parameter(Mandatory = $true)]
                [string]$managementSubscriptionId
            )
            select-azsubscription -SubscriptionId $managementSubscriptionId

            $query = "resourcecontainers
              | where type == 'microsoft.resources/subscriptions'
              | where properties['managementGroupAncestorsChain'] contains '$managementGroup'
              | project subscriptionId"

            $subscriptions = Search-AzGraph -Query $query

            foreach ($item in $subscriptions) {
                $id = [string]$item.subscriptionId
                New-AzManagementGroupSubscription -GroupName $managementGroup -SubscriptionId $id -WhatIf
                Write-Output "----------------"
            }
          }
          $params = @{
            topLevelManagementGroup = ${{ inputs.topLevelManagementGroup }}
            managementSubscription = ${{ inputs.managementSubscriptionId }}
          }

          move-subscriptions @params