name: Destory test environment

on:
  workflow_dispatch:
    inputs:
      topLevelManagementGroup:
        required: true
        default: 'gazelle-test'
      managementSubscriptionId:
        required: true
        default: 'ca29cb06-f5f6-4116-9061-493426c4d70e'

permissions:
  id-token: write
  contents: read
  
jobs:
  cancel-landingzone:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ vars.AZURE_PLATFORM_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID}}
        allow-no-subscriptions: true
        enable-AzPSSession: true

    - name: move subscriptions
      uses: azure/powershell@v2
      with:
        azPSVersion: "latest"
        inlineScript: |
          $params = @{
            topLevelManagementGroup = '${{ inputs.topLevelManagementGroup }}'
            managementSubscriptionId = '${{ inputs.managementSubscriptionId }}'
          }
          write-output $params
          ./.github/pwsh/move-subscriptions.ps1 @params