name: az - Monitoring

on:
  push:
    branches-ignore:
      - main
    paths:
        - 'src/monitoring/**'
        - 'parameters/monitoring/**'
        - '.github/workflows/template-monitoring.yml'
        - '.github/workflows/main-monitoring.yml'

  pull_request_target:
    types:
      - closed
    paths:
      - 'monitoring/**'
  
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

jobs:
  test:
    if: (github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main') ||
        github.ref != 'refs/heads/main'
    uses: ./.github/workflows/template-monitoring.yml
    with:
      managementGroupHierarchy: test
    secrets: inherit

  prod:
    if: (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') ||
         github.event.pull_request.merged == true
    uses: ./.github/workflows/template-monitoring.yml
    with:
      managementGroupHierarchy: prod
    secrets: inherit