name: az - BigBang

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Test:
    uses: ./.github/workflows/template-managementGroups.yml
    with:
      managementGroupHierarchy: test
