name: az - Init

on:
  push:
    branches-ignore:
      - main
    paths:
        - '.github/workflows/template-init.yml'
        - '.github/workflows/main-init.yml'

  pull_request_target:
    types:
      - closed
  
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

jobs:
  test:
    if: (github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main') ||
        github.ref != 'refs/heads/main'
    uses: ./.github/workflows/template-Init.yml
    with:
      managementGroupHierarchy: test
    secrets: inherit

  prod:
    if: (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') ||
         github.event.pull_request.merged == true
    uses: ./.github/workflows/template-Init.yml
    with:
      managementGroupHierarchy: prod
    secrets: inherit