name: Policy

on:
  push:
    branches-ignore:
      - main
    paths:
        - 'Policy/**'
        - '.github/workflows/template-Policy.yml'
        - '.github/workflows/main-Policy.yml'

  pull_request_target:
    types:
      - closed
    paths:
      - 'Policy/**'
  
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    if: github.event_name == 'workflow_dispatch' || 
        github.ref != 'refs/heads/main'
    uses: ./.github/workflows/template-Policy.yml
    with:
      environment: test
    secrets: inherit

  prod:
    if: (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') ||
         github.event.pull_request.merged == true
    uses: ./.github/workflows/template-Policy.yml
    with:
      environment: prod
    secrets: inherit