name: az - BigBang

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all
    environment: test
    steps:
      - name: managementGroups
        uses: ./.github/workflows/template-managementGroups.yml
        with:
          managementGroupHierarchy: test

      - name: identity
        uses: ./.github/workflows/template-Identity.yml
        with:
          managementGroupHierarchy: test