name: az - BigBang

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  mnanagementGroups:
    uses: ./.github/workflows/template-managementGroups.yml
    with:
      managementGroupHierarchy: test

  Identity:
    uses: ./.github/workflows/template-Identity.yml
    with:
      managementGroupHierarchy: test