name: gazelle - identity

on:
  push:
    branches-ignore:
      - main
    paths:
        - 'src/identity/**'
        - 'parameters/identity/**'
        - '.github/workflows/template-identity.yml'
        - '.github/workflows/main-identity.yml'

  pull_request_target:
    types:
      - closed
    paths:
      - 'src/idenitity/**'
      - 'parameters/idenitity/**'
  
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

jobs:
  test:
    if: (github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main') ||
        github.ref != 'refs/heads/main'
    uses: ./.github/workflows/template-identity.yml
    with:
      managementGroupHierarchy: test
    secrets: inherit

  prod:
    if: (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') ||
         github.event.pull_request.merged == true
    uses: ./.github/workflows/template-identity.yml
    with:
      managementGroupHierarchy: prod
    secrets: inherit