name: az - BigBang

on:
  workflow_dispatch:
    inputs:
      managementGroupHierarchy:
        description: 'Management Group Hierarchy'
        required: true
        default: 'test'
        type: choice
        options:
          - 'test'
          - 'prod'

permissions:
  id-token: write
  contents: read

jobs:
  tenant:
    uses: ./.github/workflows/template-managementGroups.yml
    with:
      managementGroupHierarchy: ${{ github.event.inputs.managementGroupHierarchy }}

  identity:
    needs: tenant
    uses: ./.github/workflows/template-Identity.yml
    with:
      managementGroupHierarchy: ${{ github.event.inputs.managementGroupHierarchy }}
    secrets: inherit

  management:
    needs: tenant
    uses: ./.github/workflows/template-monitoring.yml
    with:
      managementGroupHierarchy: ${{ github.event.inputs.managementGroupHierarchy }}
    secrets: inherit

  policy:
    needs: 
      - identity
      - management
    uses: ./.github/workflows/template-Policy.yml
    with:
      managementGroupHierarchy: ${{ github.event.inputs.managementGroupHierarchy }}
    secrets: inherit

  lz:
    needs: policy
    uses: ./.github/workflows/template-Landingzone.yml
    with:
      managementGroupName : platform
      managementGroupHierarchy: ${{ github.event.inputs.managementGroupHierarchy }}
      location: FranceCentral
      parameterFile: ./Landingzone/platform-management-${{ github.event.inputs.managementGroupHierarchy }}.json
    secrets: inherit

  