name: az - Identity

on:
  push:
    branches-ignore:
      - main
    paths:
        - 'Identity/**'
        - '.github/workflows/template-Identity.yml'
        - '.github/workflows/main-Identity.yml'

  pull_request_target:
    types:
      - closed
    paths:
      - 'Idenitity/**'
  
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  mainBicep: ./Identity/bicep/main-identity.bicep

jobs:
  test:
    if: (github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main') ||
        github.ref != 'refs/heads/main'
    uses: ./.github/workflows/template-Identity.yml
    with:
      environment: test
    secrets: inherit

  prod:
    if: (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') ||
         github.event.pull_request.merged == true
    uses: ./.github/workflows/template-Identity.yml
    with:
      environment: prod
    secrets: inherit