name: az - BigBang

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  mnanagementGroups:
    uses: ./.github/workflows/template-managementGroups.yml
    with:
      managementGroupHierarchy: test

  Identity:
    needs: mnanagementGroups
    uses: ./.github/workflows/template-Identity.yml
    with:
      managementGroupHierarchy: test

  monitoring:
    needs: mnanagementGroups
    uses: ./.github/workflows/template-monitoring.yml
    with:
      managementGroupHierarchy: test

  policies:
    needs: Identity
    uses: ./.github/workflows/template-monitoring.yml
    with:
      managementGroupHierarchy: test