
name: lz - online-MSDN-test

on:
  push:
    paths:
      - 'Landingzone/online-MSDN-test.json'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  landingzone:
    uses: ./.github/workflows/template-Landingzone.yml
    with:
      managementGroupName : online
      managementGroupHierarchy: prod
      location: FranceCentral
      parameterFile: ./Landingzone/online-MSDN-test.json
    secrets: inherit
