
name: lz - online-v1-test

on:
  push:
    paths:
      - 'Landingzone/online-v1-test.json'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  landingzone:
    uses: ./.github/workflows/template-Landingzone.yml
    with:
      managementGroupName : online
      managementGroupSuffix: prod
      location: FranceCentral
      parameterFile: ./Landingzone/online-v1-test.json
    secrets: inherit
