
name: lz - platform-management-test

on:
  push:
    paths:
      - 'Landingzone/platform-management-test.json'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  landingzone:
    uses: ./.github/workflows/template-Landingzone.yml
    with:
      managementGroupName : platform
      managementGroupSuffix: test
      location: FranceCentral
      parameterFile: ./Landingzone/platform-management-test.json
    secrets: inherit