
name: lz - platform-management-test

on:
  push:
    paths:
      - 'Landingzone/platform-management-test.json'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  landingzone:
    uses: ./.github/workflows/template-Landingzone.yml
    with:
      managementGroupName : @{labName=management; environment=test; managementGroupName=platform; managementGroupHierarchy=test; location=FranceCentral; budget=10; subscriptionId=ca29cb06-f5f6-4116-9061-493426c4d70e; githubOrganizationName=gazelle-cloud; githubRepoName=azurePlatform; ownerEmail=foo@gazelle.cloud; engineer=bar@gazelle.cloud}.managementGroupName
      managementGroupHierarchy: @{labName=management; environment=test; managementGroupName=platform; managementGroupHierarchy=test; location=FranceCentral; budget=10; subscriptionId=ca29cb06-f5f6-4116-9061-493426c4d70e; githubOrganizationName=gazelle-cloud; githubRepoName=azurePlatform; ownerEmail=foo@gazelle.cloud; engineer=bar@gazelle.cloud}.managementGroupHierarchy
      location: FranceCentral
      parameterFile: ./Landingzone/platform-management-test.json
    secrets: inherit
