
name: lz - platform-management-tst

on:
  push:
    paths:
      - 'Landingzone/parameters/platform-management-tst.json'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  landingzone:
    uses: ./.github/workflows/template-Landingzone.yml
    with:
      managementGroupName : platform
      managementGroupSuffix: tst
      location: replaceMe-lz-location
      parameterFile: ./parameters/platform-management-tst.json
    secrets: inherit
