name: template - managementGroups

on:
  workflow_call:
    inputs:
        managementGroupHierarchy:
            required: true
            type: string
        templateFile:
            default: ./managementGroups/bicep/main.bicep
            type: string
        templateParameters:
            default: ./managementGroups/parameters/managementGroups.bicepparam
            type: string

env:
  topLevelManagementGroupId: /providers/Microsoft.Management/managementGroups/${{ vars.TOP_LEVEL_MANAGEMENTGROUP_NAME }}

jobs:
    managementGroups:
        runs-on: ubuntu-latest
        environment: ${{ inputs.managementGroupHierarchy }}
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Azure login
          uses: azure/login@v2
          with:
            client-id: ${{ vars.APP_PLATFORM_INIT_CLIENT_ID }}
            tenant-id: ${{ vars.AZURE_TENANT_ID}}
            allow-no-subscriptions: true
            enable-AzPSSession: false

        - name: init RBAC
          uses: azure/cli@v2
          with:
            inlineScript: |
              az role assignment create --assignee ${{ vars.APP_PLATFORM_INIT_PRINCIPAL_ID }} \
               --role "Contributor" \
               --scope ${{ env.topLevelManagementGroupId }}

              az role assignment create --assignee ${{ vars.APP_PLATFORM_INIT_PRINCIPAL_ID }} \
               --role "Azure Deployment Stack Owner" \
               --scope ${{ env.topLevelManagementGroupId }}

        - name: management group hierarchy
          uses: azure/cli@v2
          with:
            inlineScript: |
              az deployment mg create \
               --name managementGroups \
               --location ${{  vars.AZURE_DEFAULT_LOCATION }} \
               --management-group-id ${{ vars.TOP_LEVEL_MANAGEMENTGROUP_NAME }} \
               --template-file ${{ inputs.templateFile }} \
               --parameters ${{ inputs.templateParameters }} \
               --parameters environment=${{ inputs.managementGroupHierarchy }} \
               --parameters topLevelManagementGroupName=${{ env.topLevelManagementGroupId }}