name: template - init gitHub

on:
  workflow_call:
    inputs:
        managementGroupHierarchy:
            required: true
            type: string

jobs:
    environmentVars:
        runs-on: ubuntu-latest
        environment: ${{ inputs.managementGroupHierarchy }}
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: get github token
          id: github-token
          uses: actions/create-github-app-token@v1
          with:
            app-id: ${{ vars.APP_GITHUB_BIGBANG_ID }}
            private-key: ${{ secrets.APP_GITHUB_BIGBANG }}
            owner: ${{ github.repository_owner }}

        - name: set env variables - AzurePlatform
          env:
            GH_TOKEN: ${{ steps.github-token.outputs.token }}
            MANAGEMENT_SUBSCRIPTION_ID: "INIT_MANAGEMENT_SUBSCRIPTION_ID_${{ inputs.managementGroupHierarchy }}"
            AZURE_PLATFORM_CLIENT_ID: "INIT_AZURE_PLATFORM_CLIENT_ID_${{ inputs.managementGroupHierarchy }}"
            AZURE_PLATFORM_PRINCIPAL_ID: "INIT_AZURE_PLATFORM_PRINCIPAL_ID_${{ inputs.managementGroupHierarchy }}"
          run: |
              echo "create environment"
              gh api --method PUT -H "Accept: application/vnd.github+json" \
              repos/${{ github.repository_owner }}/AzurePlatform/environments/${{ inputs.managementGroupHierarchy }}

              gh variable set MANAGEMENT_SUBSCRIPTION_ID \
                --body ${{ vars[env.MANAGEMENT_SUBSCRIPTION_ID] }} \
                --env ${{ inputs.managementGroupHierarchy }} \
                -R "${{ github.repository_owner }}/AzurePlatform"

              gh variable set AZURE_PLATFORM_CLIENT_ID \
                --body ${{ vars[env.AZURE_PLATFORM_CLIENT_ID] }} \
                --env ${{ inputs.managementGroupHierarchy }} \
                -R "${{ github.repository_owner }}/AzurePlatform"

              gh variable set AZURE_PLATFORM_PRINCIPAL_ID \
                --body ${{ vars[env.AZURE_PLATFORM_PRINCIPAL_ID ]}} \
                --env ${{ inputs.managementGroupHierarchy }} \
                -R "${{ github.repository_owner }}/AzurePlatform"

              gh variable set AZURE_PLATFORM_TEST_PRINCIPAL_ID \
                --body ${{ vars.INIT_AZURE_PLATFORM_PRINCIPAL_ID_TEST }}  \
                --env ${{ inputs.managementGroupHierarchy }} \
                -R "${{ github.repository_owner }}/AzurePlatform"

              gh variable set TOP_LEVEL_MANAGEMENTGROUP_NAME \
              --body "${{ vars.MANAGEMENTGROUP_HIERARCHY_NAME }}-${{ inputs.managementGroupHierarchy}}" \
              --env ${{ inputs.managementGroupHierarchy }} \
              -R "${{ github.repository_owner }}/AzurePlatform"

        - name: set env variables - landingzones
          env:
            GH_TOKEN: ${{ steps.github-token.outputs.token }}
            MANAGEMENT_SUBSCRIPTION_ID: "INIT_MANAGEMENT_SUBSCRIPTION_ID_${{ inputs.managementGroupHierarchy }}"
            AZURE_PLATFORM_CLIENT_ID: "INIT_AZURE_PLATFORM_CLIENT_ID_${{ inputs.managementGroupHierarchy }}"
            AZURE_PLATFORM_PRINCIPAL_ID: "INIT_AZURE_PLATFORM_PRINCIPAL_ID_${{ inputs.managementGroupHierarchy }}"
          run: |
              gh variable set AZURE_PLATFORM_CLIENT_ID \
              --body ${{ vars.INIT_AZURE_PLATFORM_CLIENT_ID_PROD }} \
              -R "${{ github.repository_owner }}/landingzones"