
name: replaceMe-landingzoneName

on:
  push:
    paths:
      - 'Landingzone/parameters/replaceMe-landingzoneName.json'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  landingzone:
    uses: ./.github/workflows/template-Landingzone.yml
    with:
      managementGroupName : replaceMe-managementGroupName
      managementGroupSuffix: replaceMe-managementGroupSuffix
      location: replaceMe-location
      parameterFile: ./parameters/replaceMe-landingzoneName.json
    secrets: inherit
