name: template - Identity

on:
  workflow_call:
    inputs:
        managementGroupHierarchy:
          required: true
          type: string

jobs:
    roleAssignments:
      runs-on: ubuntu-latest
      environment: ${{ inputs.managementGroupHierarchy }}
      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_PLATFORM_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID}}
          allow-no-subscriptions: true
          enable-AzPSSession: false

      - name: role assignments
        uses: azure/cli@v2
        with:
          azcliversion: ${{ vars.AZURE_CLI_VERSION }}
          inlineScript: |
              deployment=$(az stack mg create \
              --name identity-roleAssignments \
              --management-group-id ${{ vars.TOP_LEVEL_MANAGEMENTGROUP_NAME }} \
              --location ${{  vars.AZURE_DEFAULT_LOCATION }} \
              --template-file ./src/identity/roleAssignments.bicep \
              --parameters './parameters/identity/roleAssignments.bicepparam' \
              --parameters environment=${{ inputs.managementGroupHierarchy }} \
              --deny-settings-mode None \
              --action-on-unmanage deleteAll \
              --yes)

              envVariables=$(echo $deployment | jq '.outputs.gitHubEnviromentVariables.value')
              echo "Deployment Outputs: $envVariables"
              echo "policyIdentity=$(echo $envVariables | jq -c .)" >> $GITHUB_ENV