name: template - Policy

on:
  workflow_call:
    inputs:
        managementGroupHierarchy:
          required: true
          type: string

jobs:
    policies:
        runs-on: ubuntu-latest
        environment: ${{ inputs.managementGroupHierarchy }}
        strategy:
            matrix:
                mainBicep:
                  - foo
                scope: 
                  - online
                  - platform
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Azure login
          uses: azure/login@v2
          with:
            client-id: ${{ vars.AZURE_PLATFORM_CLIENT_ID }}
            tenant-id: ${{ vars.AZURE_TENANT_ID}}
            allow-no-subscriptions: true
            enable-AzPSSession: false

        - name: Deploy policies
          uses: azure/cli@v2
          with:
              inlineScript: |
                deployment=$(az stack mg create \
                --name testMatrix-${{ matrix.scope }} \
                --management-group-id ${{ matrix.scope }}-${{ inputs.managementGroupHierarchy }} \
                --location ${{  vars.AZURE_DEFAULT_LOCATION }} \
                --template-file ./policy/bicep/${{ matrix.scope }}.bicep \
                --parameters ./policy/parameters/${{ matrix.scope }}.bicepparam \
                --parameters location=${{  vars.AZURE_DEFAULT_LOCATION }} \
                --parameters identityResoruceId=${{  vars.POLICY_RESOURCE_ID }} \
                --parameters logAnalytics=${{ vars.LOGANALYTICS_RESOURCE_ID }} \
                --deny-settings-mode None \
                --action-on-unmanage deleteAll \
                --yes)