
name: lz - replaceMe-lz-landingzoneName

on:
  push:
    paths:
      - 'Landingzone/replaceMe-lz-landingzoneName.json'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  landingzone:
    uses: ./.github/workflows/template-Landingzone.yml
    with:
      managementGroupName : replaceMe-lz-managementGroupName
      managementGroupHierarchy: replaceMe-lz-managementGroupHierarchy
      parameterFile: ./Landingzone/replaceMe-lz-landingzoneName.json
    secrets: inherit
